services:
  - type: web
    name: hepatitis-c
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn Hep.wsgi"
    envVars:
      - key: DEBUG
        value: "False"
