# Generated by Django 5.1.3 on 2025-05-13 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HepatitisRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("AST", models.FloatField()),
                ("ALT", models.FloatField()),
                ("CHE", models.FloatField()),
                ("ALP", models.FloatField()),
                ("BIL", models.FloatField()),
                ("GGT", models.FloatField()),
                ("Age", models.FloatField()),
                ("ALB", models.FloatField()),
                ("prediction_result", models.CharField(max_length=100)),
            ],
        ),
    ]
